version: '3.1'
services:
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_DATABASE=sc2w
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./mysql-data:/var/lib/mysql
        command: "--innodb_use_native_aio=0"

    web:
        build: .
        restart: always
        stdin_open: true
        tty: true
        depends_on:
            - mysql
        volumes:
            - .:/opt/sc2w
        ports:
            - "8000:8000"
        entrypoint: /bin/bash
